name: "Build: and push to docker.io and ghcr.io"
on:
  push:
    branches:
      - master

jobs:
  docker-io:
    name: build-alpine-latest
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.BUILD_ARCH }}
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN_TRILOM }}
      - name: Login to GCHR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.BUILD_ARCH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ github.repository }}:latest
          cache-to: type=inline
